services:
  service_one:
    build:
      context: ./service_one/
    ports:
      - "8000:8000"
    environment:
      - SERVICE_TWO_URL=service_two
      - SERVICE_TWO_PORT=8001
    volumes:
      - ./service_one:/code
    stdin_open: true
    tty: true

  service_two:
    build:
      context: ./service_two/
    ports:
      - "8001:8001"
    environment:
      - SERVICE_ONE_URL=service_one
      - SERVICE_ONE_PORT=8000
    volumes:
      - ./service_two:/code
    stdin_open: true
    tty: true
